name: Build and Push Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/sasirulk/tinycloud-demo-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ARM64 image
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker buildx build \
            --platform linux/arm64 \
            -t $IMAGE_NAME:$IMAGE_TAG \
            --push .
